# Generated by Django 3.1.2 on 2021-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0005_auto_20210220_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='DateOfBirth',
            field=models.DateField(),
        ),
    ]
