# Generated by Django 3.1.2 on 2021-02-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0010_auto_20210225_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='Media',
        ),
    ]
