# Generated by Django 3.1.2 on 2021-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0011_remove_discussion_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workshop',
            new_name='Booking',
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
