# Generated by Django 3.1.2 on 2021-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0013_auto_20210331_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgrammeName', models.CharField(default='', max_length=150)),
                ('Date', models.DateField()),
                ('Session', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Workshop',
            },
        ),
    ]
