# Generated by Django 3.1.2 on 2021-04-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0016_group_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Discussion',
        ),
    ]
