# Generated by Django 3.1.2 on 2021-04-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0017_remove_group_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='NoOfEvent',
        ),
    ]
